### ISSUE TITLE
Not able to install Xion Daemon CLI on windows 

### ISSUE THREAD

**Issue by iamgauravpant** [burnt-labs/xion#138]
https://docs.burnt.com/xion/develop/getting-started/xion-daemon
Followed this documentation to install the xion daemon cli . I am using windows . Why am I not able to install this cli ?
First error that I got was the terminal could not recognize 'make' ( when we do make install ) .
To resolve it I followed this : https://stackoverflow.com/a/73862277/15612640
 Then after running 'make install' again , I got the error below :
 ![image](https://github.com/burnt-labs/xion/assets/64788558/676f1dd5-7112-4f57-a9ea-210b8f4d594c)
 How to fix this and successfully install xion daemon cli on my windows pc ?

**Comment by justinbarry** [comment]
@iamgauravpant Can you try in https://learn.microsoft.com/en-us/windows/wsl/install?

**Comment by justinbarry** [comment]
@iamgauravpant Feel free to reopen if you still have problems but I'm going to close this for now.
