### ISSUE TITLE
Implement interchaintests for fee-abstraction

### ISSUE THREAD

**Issue by froch** [burnt-labs/xion#154]
Problem Domain:

- We have made good progress for our initial foray into [fee-abstraction](https://github.com/osmosis-labs/fee-abstraction)
- We want to add tests to keep the success state of what we've achieved truthful
- We want to reproduce the failures we've encountered locally in unit tests

Solution:

- Rework the [first stab implementation](https://github.com/burnt-labs/xion/compare/main...froch/feeabs) that led to a transient dependency loop
- Revise the strategy through which all chains successfully boot and produce blocks
- Follow-up with Strangelove about booting `nobled` genesis test nodes correctly. It's quite interesting what they did / do on genesis boot, but tricky.

**Comment by edjroz** [comment]
Should this issue be closed, or reassigned ? @justinbarry @2xburnt

**Comment by froch** [comment]
hey guys! i'll bow out of this issue, if any takers want it. might be, it's no longer relevant either.

**Comment by firsthokage100** [comment]
@froch so true 
Let wait and see
