### ISSUE TITLE
Failed to run a node

### ISSUE THREAD

**Issue by jeff2857** [burnt-labs/xion#174]
I followed the doc (https://docs.burnt.com/xion/nodes-and-validators/run-a-node) of running a node step by step, but at the last step `xiond start --x-crisis-skip-assert-invariants --home /home/xiond/.xiond`, it outputs an error `error on loading last version err="failed to load latest version: version of store jwk mismatch root store's version; expected 6770829 got 0; new stores should be added using StoreUpgrades" module=server`, any solutions?

OS: Ubuntu 22.04.3 LTS
go version: 1.21.8
xiond version: 0.3.6-2-ge301403

**Comment by justinbarry** [comment]
What version of the xiond binary are you using?

**Comment by jeff2857** [comment]
> What version of the xiond binary are you using?

0.3.6-2-ge301403

**Comment by jeff2857** [comment]
I downgraded `xiond` to version `0.3.4`, and the problem solved
