### ISSUE TITLE
Node start failed when trying to parse genesis

### ISSUE THREAD

**Issue by firmianavan** [burnt-labs/xion#205]
The error log(please ignore 'mainnet' in wallet-xion-mainnet-01, just container name):
<img width="1728" alt="image" src="https://github.com/burnt-labs/xion/assets/25193549/9f710247-9320-4cfd-b325-e21439fd0be7">

My Dockerfile:
```
FROM burntnetwork/xion:latest

WORKDIR /home/xiond

COPY run.sh /home/xiond/run.sh

EXPOSE 1317

ENTRYPOINT ["/bin/bash", "/home/xiond/run.sh"]
```

And the run.sh used in the Dockerfile:
```
#!/bin/bash
if [ ! -f "/home/xiond/.xiond/config/genesis.json" ];then
    xiond init ttt --chain-id xion-testnet-1 --home /home/xiond/.xiond
    cd /home/xiond/.xiond/config/
    wget -O addrbook.json   https://files.xion-testnet-1.burnt.com/addrbook.json
    wget -O genesis.json https://files.xion-testnet-1.burnt.com/genesis.json
    sed -i 's/laddr = "tcp:\/\/localhost:1317"/laddr = "tcp:\/\/0.0.0.0:1317"/g' app.toml
    sed -i 's/laddr = "tcp:\/\/127.0.0.1:26658"/laddr = "tcp:\/\/127.0.0.1:26658"/g' config.toml
    sed -i '0,/enable = false/s/enable = false/enable = true/' app.toml
fi

xiond start --x-crisis-skip-assert-invariants --home /home/xiond/.xiond
```

**Comment by ash-burnt** [comment]
There have been several versions from genesis, you would need to start with the original version and upgrade in order:

## `xion-testnet-1` upgrade path

| Git Tag  | Docker Tag    | Git SHA                                    | Block Height | Requires Halt |
|----------|---------------|--------------------------------------------|--------------|---------------|
| `v0.1.0` | `sha-2722f0f` | `2722f0fb1234db97e9bf9b98f744675eb8fb1b26` | `0`          | false         |
| `v0.3.2` | `sha-455cfa5` | `455cfa5b78e79e1c50867f6d61a99b0e9df6b9b1` | `1929544`    | true          |
| `v0.3.3` | `sha-79f0d91` | `79f0d91dfcd4c5916fa30ea246eed1677daf4e44` | `2147030`    | true          |
| `v0.3.4` | `sha-74754c7` | `74754c7c206a7d0f27a23ac9431a4d09dbacff4c` | `3278095`    | false         |
| `v0.3.7` | `sha-f13a74c` | `f13a74c7cf5a562d6902263e53c5ee4f0a9dfefe` | `6887750`    | true          |
| `v0.3.8` | `sha-34c82a9` | `34c82a927b7ae7b67e8b76a1a66fe1b36f807f82` | `7130100`    | true          |
| `v0.3.9` | `sha-9667057` | `96670570350b6dc885dbdeb0bd03e37830b512b1` | `7438800`    | true          |

**Comment by firmianavan** [comment]
Resolved when I used node data snapshot, thank you so much.
