### ISSUE TITLE
Mint Module changes tests

### ISSUE THREAD

**Issue by Peartes** [burnt-labs/xion#38]
The changes to the mint module to control the inflation of the Xion tokens need to be tested.

The details of the changes can be found [here](https://www.notion.so/78f59fb108c04e9ea5fa826dda30a340)

The tests cases need to satisfy this constraint to be said to function properly

## Setting up the app:
An important step to consider are the initial parameters of the app used for the test case. These parameters are:
- Initial Inflation Rate (IFR)
- Initial total token  (ITR)
- Initial staked token (IST)

## Base Case - No Transaction in block 
- Use the default values above to set up this test case
- In this case, the result should show over multiple blocks that the inflation rate increases over time
- The mint module must have minted Summation(inflation_rate(t) * staked_tokens)(t) i.e. the summation over time of the inflation rate at a particular time * the staked tokens 

## Transaction case - Over Target Return
- For this case, initiate a transaction with a very high fee i.e. fee > IFR * staked_tokens.
- The result should show that the mint module minted no new token
- The mint module burnt some tokens equal to fee - (IFR * staked_tokens)

## Transaction case - Under Target Return
- For this case, initiate a transaction with a very small fee i.e. fee << IFR * staked_tokens.
- The result should show that the mint module minted new token
- The mint module minted some tokens equal to (IFR * staked_tokens)

## Transaction case - At Target Return
- For this case, initiate a transaction with a fee equal to IFR * staked_tokens.
- The result should show that the mint module does not mint new token
- The mint module does not burn any token

## NB
Staked tokens stay constant over the period of this test and further improvement would be to test the module on changing staked tokens

**Comment by edjroz** [comment]
These tests have been covered in #45 #47, great work!
